@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.alexbrumbart.postalpigeons.util;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;