@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.alexbrumbart.postalpigeons.blocks;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;