@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package de.alexbrumbart.postalpigeons.entity;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;